name: Dummy Trigger
on:
  push:
    branches: [master]
    paths:
      - '.github/workflows/dummy.yml'
jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering workflow discovery"
